name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with pylint
      run: |
        pylint app.py test_app.py || true

    - name: Test with unittest
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python -m unittest test_app.py

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push to dockerhub
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: arnavj1903/disease-prediction-system:latest
       build-args: |
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build static files
      run: |
        mkdir -p build
        cp -r templates/* build/
        cp -r static/* build/
        # Copy any other static assets
        cp .nojekyll build/ || true
        cp _config.yml build/ || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        force_orphan: true